fastq_folder: "results/exomes/bbduk_trimmed"
aligned_folder: "results/exomes/aligned"
output_folder: "results/exomes"
final_bam_folder: "results/exomes/bqsr"
log_dir_sub: "logs"
reference: "analysis/ref/GRCh38/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna.gz"
reference_unpacked: "analysis/ref/GRCh38/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna"
panel_of_normals: "analysis/GATK_resource_bundle/1000g_pon.hg38.vcf.gz"
af_only_gnomad: "analysis/GATK_resource_bundle/af-only-gnomad.hg38.vcf.gz"
common_biallelic_gnomad: "analysis/GATK_resource_bundle/af-only-gnomad.hg38.common_biallelic.vcf.gz"
reference_version: "GRCh38"
final_bam_file_extension: ".merged.dedup.bqsr.bam"
metadata_file: "metadata/metadata_exomes.tsv"